# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# modified for bioconductor following https://gist.github.com/lcolladotor/bfe6e309fc13c219dfd8f6616a681013/revisions
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      LANG: en_US.UTF-8  # Ensure consistent encoding
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Install required locale
        if: runner.os == 'Linux'
        run: sudo apt-get install -y locales && sudo locale-gen en_US.UTF-8

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install BiocManager
        run: |
          install.packages("remotes")
          remotes::install_cran("BiocManager")
        shell: Rscript {0}

      - name: Install dependencies from bioconductor
        run: |
          BiocManager::install("biomaRt")
        shell: Rscript {0}
        
      - name: Install other dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: List files for debugging
        run: ls -R

      - name: Print file content for debugging
        run: cat test_data/test_bim.bim || echo "File not found"
        shell: bash

      - name: Run check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
